env = Environment()
env.Append(CCFLAGS = ['-std=c++11', '-stdlib=libc++'])
env.Append(CPPPATH = ['../../'])
env.Append(LINKFLAGS = ['-stdlib=libc++'])
program = env.Program( 'test', ['main.cpp' ] )

testAlias = Alias( 'test', [program], program[0].path )
